experiment: Joint Optimization for 2D RF & Gradient Pulse Design
exp_name: exp_pTx_G_RF_SI_0413_7ms

image:
  dir: data/masked_dataset
  fov: [ 0.28, 0.28 ]
  N: [ 64, 64 ]

magnet:
  ex_mode: 2
  tx: 8
  gamma: 2.67522e+8
  tp: 7.15e-3
  fa: 90
  scale: 4e-1
  use_fm_generator: false
  grad_path: data/pulse/Gpulse_JR_kmax_70.txt
  si_path: data/pulse/example_update.npz
  mask_path: null
  gmax: 4.2e-2
  smax: 2.25e+2
  offset_hz: 0
  block_steps: 256

model:
  in_dim: 3
  rf_output_dim: 1430
  grad_output_dim: 4
  norm: group
  act: swish
  block: [ 3, 4, 6, 3 ]

train:
  deterministic: true # true for ablation/debug, false for production
  seed: 123
  joint: true
  num_samples: 8000
  batch_size: 64
  epochs: 800
  fm_resample_every_epochs: 50 # resample every N epochs
  lr: 1e-3
  dropout: 1e-1
  val_iter: 1
  grad_clip_norm: 0.0
  lambda_ssim: 1.0
  lambda_psnr: 1.0
  lambda_rmse: 1.0
  lambda_iou: 1.0
  lambda_rf_re_amp: 1e-1
  lambda_rf_im_amp: 1e-1
  lambda_rf_re_smooth: 1e-1
  lambda_rf_im_smooth: 1e-2
