[project]
name = "selexnet"
version = "0.1.0"
description = "SelExNet: A Self-Supervised Physics-Informed Framework for Multi-Channel Joint RF and Gradient Waveform Optimization in 2D Spatially Selective Excitation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "matplotlib>=3.9.4",
  "matplotlib-inline>=0.2.2",
  "numpy>=2.0.2",
  "omegaconf>=2.3.1",
  "opencv-python>=5.0.0.93",
  "pillow>=11.3.0",
  "pytorch-msssim>=1.0.0",
  "scipy>=1.13.1",
  "torch>=2.8.0",
  "torch-pca>=1.1.0",
  "tqdm>=4.70.1",
]

[project.scripts]
selexnet = "selexnet:main"

[project.optional-dependencies]
all = [
  "pydicom>=2.4.4",
  "scikit-image>=0.24.0",
  "scikit-learn>=1.6.1",
  "torchvision>=0.23.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "black>=25.11.0",
  "flake8>=7.3.0",
  "isort>=6.1.0",
  "jupyterlab>=4.5.10",
  "mypy>=1.19.1",
  "pytest>=8.4.2",
]
